---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--color --format documentation'\""
  extras:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="3.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="3.7.0"
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  matrix_extras:
    - PUPPET_GEM_VERSION: 3.7.0
      RUBY_VER: 193
    - PUPPET_GEM_VERSION: 3.7.0
      RUBY_VER: 200-x64
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2015
      end: 'latest'
