---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  include_todos: true
".travis.yml":
  global_env:
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  deploy_to_forge:
    enabled: false
  simplecov: true
  notifications:
    slack:
      secure: >-
        ApkHaUgp5NAEE8Zb+hlbR7g6OLsbp3VP48yU0hflwKVALYJUzrNQAwa4AxSpLCfaTU3GR7JrNunp5P8/oOqjU+ZxCdKxuwaJ+4xZ8tb+uFWQOeFuGKDSzcX90Vu4k5sniNdP3r/ezMDRNgChFre6+jUT7vo9MvNbIN1coYWPlxK/3JVvxM9nS9TwW1GXv2sZ7a6TYcs/N2sStfStFUEO+ffZEnUsmzlIy3YwnpeGw/1KLOmkyTFT90qRDwNGsSimFacJLBcUlgZpxUhzfPBo/RqSxjwYLTP9Q+Uvx0wg+xd0znazxBg69mE1p3j2bGw51uVt45odYqU/s6F5J3rNBG6nFMjHqt7vhWBcqNwRV2k8zJBtIcXFYtfshmGuNYhSVSJ6vZNm0EJ/k8wwkXTx+OJb2q86Eqice6SnS9vfnhqhOR4Ud4UjTO2hiJzIm6GnOjKoXnW0342PDOlvxiU0Tm/FdXniyaZr5vx8PQtUfE1wigx1vO1KaPSyNU1gcAl3PVU5OIHFTGSHN0XUKHfzNOLFcoN02PhejZzItlfVYwrtns4Ge2nxVsT1+fhxF4mtcmhuJ1dBOoo/cxKAwK20C/tKA2Mz2a0uEVe75r8+mMeh1K82A2++iNK/aYsZn8IQs92CqLZwrHC+X2VNyfUvMCgxjNBzGPLfVLrrElYhsmA=
appveyor.yml:
  environment:
    HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
    HONEYCOMB_DATASET: litmus tests
  matrix_extras:
  - RUBY_VERSION: 24-x64
    CHECK: spec_pester
  - PUPPET_GEM_VERSION: "~> 6.0"
    RUBY_VERSION: 25
    CHECK: parallel_spec
  - PUPPET_GEM_VERSION: "~> 6.0"
    RUBY_VERSION: 25-x64
    CHECK: parallel_spec
  simplecov: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')
Rakefile:
  extras:
  - desc "Run PowerShell unit tests"
  - task :spec_pester do
  - '  exec ("powershell -NoProfile -NoLogo -NonInteractive -Command \". spec/run_pester.ps1 -EnableExit\"")'
  - end
spec/spec_helper.rb:
  coverage_report: true

.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false

.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: true
  delete: true
