---
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true

Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      version: '= 1.15.2'
Rakefile:
  extras:
  - desc "Run PowerShell unit tests"
  - task :spec_pester do
  - '  exec ("powershell -NoProfile -NoLogo -NonInteractive -Command \". spec/run_pester.ps1 -EnableExit\"")'
  - end
spec/spec_helper.rb:
  coverage_report: true

.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false

.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: true
  delete: true
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
