version: 1.0.x.{build}
skip_commits:
  message: /(^\(?doc\)?.*|.*[A|a]cceptance [T|t]est.*)/
clone_depth: 10
init:
- SET
- 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
environment:
  matrix:
  - PUPPET_GEM_VERSION: 3.4.3
    RUBY_VER: 193
  - PUPPET_GEM_VERSION: 3.7.5
    RUBY_VER: 193
  - PUPPET_GEM_VERSION: 3.7.5
    RUBY_VER: 200-x64
  - PUPPET_GEM_VERSION: 4.0.0
    RUBY_VER: 21
  - PUPPET_GEM_VERSION: 4.0.0
    RUBY_VER: 21-x64
matrix:
  fast_finish: true
install:
- SET PATH=C:\Ruby%RUBY_VER%\bin;%PATH%
- gem install bundler --quiet --no-ri --no-rdoc
- bundle install --jobs 4 --retry 2 --without development
- type Gemfile.lock
build_script:
- 'bundle exec puppet apply -e "user {''Administrator'': ensure=>present, password => ''Th!s1sS#cur3@@@2129021'', groups=>[''Administrators''],}" && exit 0'
test_script:
- bundle exec puppet -V
- ruby -v
- bundle exec rspec spec/unit spec/integration -fd -b
notifications:
- provider: Email
  to:
  - nobody@nowhere.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false

